#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["test/RecipeApplication.Tests/RecipeApplication.Tests.csproj", "test/RecipeApplication.Tests/"]
COPY ["src/RecipeApplication/RecipeApplication.csproj", "src/RecipeApplication/"]
RUN dotnet restore "test/RecipeApplication.Tests/RecipeApplication.Tests.csproj"
COPY . .
WORKDIR "/src/test/RecipeApplication.Tests"
RUN dotnet test
