version: "3.8"
services:
        nginx:
                build: ./Nginx
                links:
                        - recipe:recipe
                ports:
                        - "80:80"
        recipe:
                build: ./src/RecipeApplication
                ports:
                        - "80"
                depends_on:
                        - nginx
